services:
  database:
    image: mongo
    restart: always

  web:
    build: .
    restart: always
    ports:
        - 5261:5261
    depends_on:
      - database
    volumes:
      - ./:/URLShortner/
    environment:
      link: "mongodb://database:27017/"
      SECRET_KEY: "secret"
      google_client_id: "google_client_id"
      google_client_secret: "google_client_secret"
    env_file:
      - .env
